package entity

type Car struct {
	ID uint `json:"id"`
	Name string `json:"name"`
  Grade string
  "manufacture" varchar(255)
  "model_year" varchar(255)
  "model_number" varchar(255)
  "body_type" varchar(255)
  "door_num" int
  "color" varchar(255)
  "drive_system" varchar(255)
  "transmission" varchar(255)
  "displacement" int
  "gas_oil" varchar(255)
  "seating_capacity" int
  "ex_point" int
  "in_point" int
  "one_owner" int
  "repair_history" int
  "non_smoking" int
  "certified_used" int
  "recycling_consignment" int
  "leagal_maintenance" int
  "warranty" int
  "purchase_price" int
  "description" varchar(255)
  "pw_steering" int
  "pw_window" int
  "aircon" int
  "w_aircon" int
  "keyless" int
  "smart_key" int
  "car_nabigation" int
  "tv" int
  "audio" int
  "visual" int
  "bluetooth" int
  "usb" int
  "pw_supply" int
  "back_camera" int
  "around_camera" int
  "etc" int
  "third_seat" int
  "ele_seat" int
  "seat_heater" int
  "seat_aircon" int
  "leather_seat" int
  "slide_door" int
  "ele_gate" int
  "walk_through" int
  "cruise_control" int
  "lane_assist" int
  "obstacle_sensor" int
  "auto_parking" int
  "parking_assist" int
  "abs" int
  "stability_control" int
  "mitigation_brake" int
  "head_light" int
  "sun_roof" int
  "aero" int
  "al_wheel" int
  "low_down" int
  "lift_up" int
  "super_charger" int
  "air_suspension" int
  "create_at" datetime
  "update_at" datetime
  "delete_at" datetime
}
